enum ActionType {
    CLEAR_USER_DATA,

    INCREMENT = 100, // unique range!
    DECREMENT,

    NEW_VIEWPORT,

    REGISTER_TRIGGER_VISIBLE = 200,
    REGISTER_UPDATE_DATA,
    REGISTER_UPDATE_DIRTY_FIELDS,
    REGISTER_UPDATE_ERRORS,
    REGISTER_SEND,
    REGISTER_SUCCESSFUL,
    REGISTER_FAILED,

    LOGIN_TRIGGER_VISIBLE = 300,
    LOGIN_UPDATE_DATA,
    LOGIN_UPDATE_DIRTY_FIELDS,
    LOGIN_SEND,
    LOGIN_SUCCESSFUL,
    LOGIN_FAILED,

    RESET_TRIGGER_VISIBLE = 400,
    RESET_UPDATE_DATA,
    RESET_UPDATE_DIRTY_FIELDS,
    RESET_SEND,
    RESET_SUCCESSFUL,
    RESET_FAILED,

    RESTORE_UPDATE_DATA = 500,
    RESTORE_SEND,
    RESTORE_SUCCESSFUL,
    RESTORE_FAILED,

    ALERT_TRIGGER_VISIBILITY = 600,
    ALERT_UPDATE_DATA,

    SET_NAME_VALIDITY,
    SET_PHONE_NUMBER,
    SET_PHONE_NUMBER_VALIDITY,
    SET_MOBILE_VERIFICATION_CODE,
    SET_USER_MOBILE_VERIFICATION_CODE,
    SET_MOBILE_VERIFICATION_CODE_VALIDITY,
    PRELOAD_IDENTITY_FILE,
    PRELOAD_IDENTITY_FILE_COMPLETED,
    SAVE_IDENTITY_FILES,
    SAVE_IDENTITY_FILES_COMPLETED,

    MENU_TRIGGER_VISIBILITY = 800,
    MENU_TRIGGER_SEARCH,
    MENU_GET_SEARCH_DATA,

    USER_LOGGED_STATUS = 900,

    DATA_UPDATE_EFFECTS_LIST = 1000,

    SET_PRODUCT_CATEGORIES,
    SET_ACTIVITY_GROUPS,
    SET_FEATURED_PRODUCTS,
    SET_TRENDING_PRODUCTS,

    LOAD_TRENDING_DISPENSARIES = 1100,
    LOAD_TRENDING_DISPENSARIES_COMPLETE,

    ADD_TO_CART,
    REMOVE_FROM_CART,

    SET_GOOGLE_STATUS,
    SET_FACEBOOK_STATUS,

    SET_STATES_LIST,
    SELECT_STATE,
    CHANGE_STATE,

    SET_MEDICAL_STATUS,
    SET_CURRENT_USER,

    SET_SHOP_SHIPMENT,
    SET_SHOP_FILTER,
    SET_SHOP_PRODUCTS,

    IS_USER_EMAIL_TAKEN,
    PASSWORD_CHANGE_STATUS
}

export default ActionType;
